# syntax=docker/dockerfile:1.5

# We do not use AG DLC as we may need to benchmark against any specific version of AG
# This saves space when pulling a smaller sized image

# Select either the CPU or GPU Image depending on if you are running GPU experiments or not.
# While CPU experiments can be ran on the GPU Image, it will be more cumbersome due to the much larger image size.

# CPU Image (Small, w/o cuda)
FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.5.1-cpu-py311-ubuntu22.04-sagemaker

# GPU Image (Large, w/ cuda)
# FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.5.1-gpu-py311-cu124-ubuntu22.04-sagemaker

# Source install Autogluon mainline or any branch that the user wants to benchmark against
# User can also source install tabrepo or any other libraries, if required
# Make sure to delete the copy statements if you clone the repos and install it in the Dockerfile

RUN cd workspace && git clone https://github.com/autogluon/autogluon
RUN ./workspace/autogluon/full_install.sh

# Delete the below line if you clone the tabrepo repo and source install it in the Dockerfile
COPY tabrepo /workspace/tabrepo
COPY tabprep /workspace/tabprep
COPY ./tabrepo/tabflow/tabflow/cli/evaluate.py .
RUN chmod +x ./evaluate.py

WORKDIR /workspace

# Delete uv cache to save ~3.5 GB of space
# Comment out to instead install the latest official release via pip.
RUN set -ex && \
    git clone --depth 1 https://github.com/autogluon/autogluon && \
    ./autogluon/full_install.sh && \
    uv cache clean && \
    uv cache prune && \
    pip uninstall -y uv && \
    rm -rf ~/.cache/uv

# Delete the below line if you clone the tabrepo repo and source install it in the Dockerfile
COPY tabrepo/ tabrepo/

# Create weights directory and copy local weights to workspace
# RUN mkdir -p workspace/weights
# COPY weights/* workspace/weights/

# Install the required packages
RUN pip install -e workspace/tabrepo/[benchmark]
RUN pip install -e workspace/tabrepo/tabflow/

# GPU images can come pre-installed with flash-attn, uncomment this to ensure it isn't installed
# RUN pip uninstall flash-attn -y

# Generate tabrepo configs and give permissions
# RUN chmod +x ./workspace/tabrepo/scripts/run_generate_all_configs.py
# RUN python ./workspace/tabrepo/scripts/run_generate_all_configs.py
RUN chmod +x ./evaluate.py
